import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftNav from "./_leftNav/page";
import RightNav from "./_rightNav/page";
import Header from "./_header/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${inter} bg-black text-white`}>
        <div className="flex min-h-screen flex-col">
          <Header />
          <div className="flex flex-1 flex-col sm:flex-row">
            <main className="flex-1 ">{children}</main>
            <LeftNav />
            <RightNav />
          </div>

          <footer className="text-center italic opacity-10">
            By using this site you are OK with selling your soul.
          </footer>
        </div>
      </body>
    </html>
  );
}
